name: main job
run-name: ${{ github.actor }} runs main
on:
  push:
    branches: [main, ci-concurrently]
  pull_request:
    branches: [main, ci-concurrently]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Starting node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm ci
      - name: linting
        run: npm run lint
        run: npm run stylelint
        run: npm run tsc
      - name: tests
        npm: npm run test
      - name: build
        run: npm run build